# Project tasks are loaded only after build:run-task is invoked.
task=build-headless
executable=haxeon/scripts/haxeon
cwd=.
argument=build
argument=--project
argument=haxeon.json

task=test-headless
executable=./scripts/test.sh
cwd=.

task=build-uikit
executable=./scripts/build.sh
cwd=.
