#!/usr/bin/env python3
"""Embed the pinned Seti font and filename/extension mappings. Requires fonttools."""
import base64
import io
import json
import re
from collections import defaultdict
from pathlib import Path
from fontTools.ttLib import TTFont

root = Path(__file__).resolve().parent.parent
assets = root / 'graphical/assets/seti'
theme = json.loads((assets / 'vs-seti-icon-theme.json').read_text())
languages = json.loads((assets / 'vscode-language-associations.json').read_text())
# Seti's explicit associations override the language fallback, as in VS Code.
for category in ['fileNames', 'fileExtensions']:
    fallback = {name.lower(): theme['languageIds'][language] for name, language in languages[category].items()}
    fallback.update({name.lower(): icon for name, icon in theme[category].items()})
    theme[category] = fallback
font = TTFont(assets / 'seti.woff', recalcTimestamp=False)
font.flavor = None
stream = io.BytesIO()
font.save(stream)
encoded = base64.b64encode(stream.getvalue()).decode('ascii')
lines = ['package ui;', '', 'import haxe.io.Bytes;', '',
         '// Generated by scripts/generate-seti-icons.py. See graphical/assets/seti for licenses.',
         'class SetiIconData {', '\tpublic static function fontData():Bytes {',
         '\t\t// Decode through byte indexing: Unicode string indexing is costly on Wasm.',
         '\t\tvar encoded = Bytes.ofString(' + json.dumps(encoded) + ');',
         f'\t\tvar decoded = Bytes.alloc({len(stream.getvalue())});',
         '\t\tvar input = 0, output = 0;',
         '\t\twhile (output < decoded.length) {',
         '\t\t\tvar value = (digit(encoded.get(input)) << 18) | (digit(encoded.get(input + 1)) << 12) |',
         '\t\t\t\t(digit(encoded.get(input + 2)) << 6) | digit(encoded.get(input + 3));',
         '\t\t\tinput += 4;',
         '\t\t\tdecoded.set(output++, (value >> 16) & 255);',
         '\t\t\tif (output < decoded.length) decoded.set(output++, (value >> 8) & 255);',
         '\t\t\tif (output < decoded.length) decoded.set(output++, value & 255);',
         '\t\t}', '\t\treturn decoded;', '\t}', '',
         '\tstatic inline function digit(value:Int):Int {',
         '\t\tif (value >= 65 && value <= 90) return value - 65;',
         '\t\tif (value >= 97 && value <= 122) return value - 71;',
         '\t\tif (value >= 48 && value <= 57) return value + 4;',
         '\t\treturn value == 43 ? 62 : value == 47 ? 63 : 0;', '\t}', '',
         '\tpublic static function iconId(filename:String):String {',
         '\t\tvar name = filename.toLowerCase();', '\t\tswitch (name) {']

def emit_cases(mapping, indent):
    grouped = defaultdict(list)
    for name, icon in sorted(mapping.items()):
        grouped[icon].append(name.lower())
    for icon, names in sorted(grouped.items()):
        lines.append(indent + 'case ' + ', '.join(json.dumps(n) for n in sorted(set(names))) + ': return ' + json.dumps(icon) + ';')

emit_cases(theme['fileNames'], '\t\t\t')
lines += ['\t\t\tdefault:', '\t\t}', '\t\t// Longest compound extension first, then shorter suffixes.',
          '\t\tvar dot = name.indexOf(".");', '\t\twhile (dot >= 0) {',
          '\t\t\tname = name.substring(dot + 1);', '\t\t\tswitch (name) {']
emit_cases(theme['fileExtensions'], '\t\t\t\t')
lines += ['\t\t\t\tdefault:', '\t\t\t}', '\t\t\tdot = name.indexOf(".");', '\t\t}',
          '\t\treturn ' + json.dumps(theme['file']) + ';', '\t}', '',
          '\tpublic static function definition(id:String, dark:Bool):SetiIconDefinition {', '\t\treturn switch (id) {']
for icon, definition in sorted(theme['iconDefinitions'].items()):
    if icon.endswith('_light'):
        continue
    light = theme['iconDefinitions'].get(icon + '_light', definition)
    definition = dict(definition, fontColor=definition.get("fontColor", "#d4d7d6"))
    light = dict(light, fontColor=light.get("fontColor", "#627379"))
    code = int(re.search(r'[0-9A-Fa-f]+$', definition['fontCharacter']).group(), 16)
    lines.append(f'\t\t\tcase {json.dumps(icon)}: new SetiIconDefinition({json.dumps(chr(code), ensure_ascii=False)}, dark ? 0x{definition["fontColor"][1:]} : 0x{light["fontColor"][1:]});')
lines += ['\t\t\tdefault: definition("_default", dark);', '\t\t};', '\t}', '}', '']
(root / 'graphical/src/ui/SetiIconData.hx').write_text('\n'.join(lines))
print(f'Embedded {len(stream.getvalue())} font bytes and {len(theme["fileExtensions"])} extension associations')
